# Generated by Django 4.1.1 on 2022-12-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='make',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='material',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('R', 'Red'), ('B', 'Blue'), ('Y', 'Yellow'), ('MP', 'Mirror Polish')], default='Pick Color', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
