# Generated by Django 4.1.1 on 2022-12-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_order_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('R', 'Red'), ('B', 'Blue'), ('Y', 'Yellow'), ('MP', 'Mirror Polish')], default='None', max_length=20),
        ),
    ]
