# Generated by Django 4.1.1 on 2022-12-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('R', 'Red'), ('B', 'Blue'), ('Y', 'Yellow'), ('Bl', 'Black'), ('MP', 'Mirror Polish'), ('C', 'Custom')], default='Black', max_length=20),
        ),
    ]
